on: push

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: make
    - run: make check
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - run: make
    - run: make check
  build-self-hosted:
    strategy:
      matrix:
        cc: [cc]
    runs-on: debian12-agent
    steps:
    - uses: actions/checkout@v4
    - run: CC=${{ matrix.cc }} make
    - run: CC=${{ matrix.cc }} make check
